### ISSUE TITLE
Not really an issue....

### ISSUE THREAD

**Issue by kerk1v** [Graylog2/graylog-contentpack-nginx#3]
I have added the $host field which may be is useful for these running several virtual Hosts on one Nginx instance to this excellent Graylog2 Content Pack. Find it here: 

https://git.spainip.es/open-source/graylog_nginx_content_pack

I am not familiar with pull requests and stuff like this, so please someone feel free to take care of this, if you like my humble contribution.

**Comment by aiv** [comment]
I do the same in my version but base on $http_host. This is really useful.

**Comment by jalogisch** [comment]
@aiv maybe you can create a PR with that

**Comment by aiv** [comment]
Sure. I will do it in 2 days.

**Comment by kerk1v** [comment]
Thanks!
